Allow base name of resource to be longer
When trying to run this script for knative/build-pipeline, the resource
name was getting truncated too early: 1) the resource names were all the
same and 2) they were invalid because they happened to end with `-`.

This resulted in errors like:
```
ERROR: (gcloud.compute.networks.describe) Could not fetch resource:
 - Invalid value 'kbuild-pipeline-e2e-'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?'
```

30 chars is pretty arbitrary so open to better solutions also!

This is for https://github.com/knative/build-pipeline/issues/16